### ISSUE TITLE
App crashes on opening a channel

### ISSUE THREAD

**Issue by ghost** [broscr/IPTV-Player#26]
App crashes right after clicking on a channel.
Is there a way to provide logs of any sorts?

Android Version : 13
[https://rimgo.projectsegfau.lt/MWdEJTu.jpeg](https://rimgo.projectsegfau.lt/MWdEJTu.jpeg)

**Comment by Toroop78** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
	at com.broscr.iptvplayer.utils.Helper.detectDashType(Helper.java:39)
	at com.broscr.iptvplayer.ui.activitys.player.PlayerActivity.setMediaItem(PlayerActivity.java:250)
	at com.broscr.iptvplayer.ui.activitys.player.PlayerActivity.createMediaItems(PlayerActivity.java:236)
	at com.broscr.iptvplayer.ui.activitys.player.PlayerActivity.initializePlayer(PlayerActivity.java:104)
	at com.broscr.iptvplayer.ui.activitys.player.PlayerActivity.onStart(PlayerActivity.java:184)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1563)
	at android.app.Activity.performStart(Activity.java:8570)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3922)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2437)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8294)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
