### ISSUE TITLE
App crashing when trying to play

### ISSUE THREAD

**Issue by workprofilesession** [broscr/IPTV-Player#28]
The app is crashing while trying to play any channel

**Comment by broscr** [comment]
If you share the crash log I can take a check.

**Comment by workprofilesession** [comment]
"FATAL EXCEPTION: main
Process: com.broscr.iptvplayer, PID: 12901
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at j$.util.Objects.requireNonNull(Unknown Source:0)
	at com.broscr.iptvplayer.ui.activitys.player.PlayerActivity.setMediaItem(PlayerActivity.java:250)
	at com.broscr.iptvplayer.ui.activitys.player.PlayerActivity.createMediaItems(PlayerActivity.java:236)
	at com.broscr.iptvplayer.ui.activitys.player.PlayerActivity.initializePlayer(PlayerActivity.java:104)
	at com.broscr.iptvplayer.ui.activitys.player.PlayerActivity.onStart(PlayerActivity.java:184)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1704)
	at android.app.Activity.performStart(Activity.java:9003)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4018)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:327)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:307)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:279)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)" This one

and 

    "FATAL EXCEPTION: main
Process: com.broscr.iptvplayer, PID: 12713
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1064093653, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/... flg=0x1 }} to activity {com.broscr.iptvplayer/com.broscr.iptvplayer.ui.activitys.fileselect.FileSelectActivity}: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5815)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5854)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:69)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at com.broscr.iptvplayer.filereader.FileReader.readFile(FileReader.java:67)
	at com.broscr.iptvplayer.ui.activitys.fileselect.FileSelectActivity.lambda$initialize$0(FileSelectActivity.java:59)
	at com.broscr.iptvplayer.ui.activitys.fileselect.FileSelectActivity.$r8$lambda$75rQVlVwA7LoXDaId-1MuUflTS4(Unknown Source:0)
	at com.broscr.iptvplayer.ui.activitys.fileselect.FileSelectActivity$$ExternalSyntheticLambda0.onActivityResult(Unknown Source:4)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:414)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:371)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:845)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
	at com.broscr.iptvplayer.ui.activitys.fileselect.FileSelectActivity.onActivityResult(FileSelectActivity.java:112)
	at android.app.Activity.internalDispatchActivityResult(Activity.java:9340)
	at android.app.Activity.dispatchActivityResult(Activity.java:9324)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5807)"
